# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - richardhawkinslanding

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_1528a30b5d32401385acfd5102e35647 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b53f4a22f35e4ddaaf588eb161658f13 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1528a30b5d32401385acfd5102e35647 }}/hawkinsr/rhmelanding:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'richardhawkinslanding'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a0fcb50015014dcd858314b2b958a724 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1528a30b5d32401385acfd5102e35647 }}/hawkinsr/rhmelanding:${{ github.sha }}'