name: Build and deploy container app to Azure Web App - richardhawkinslanding

on:
  push:
    branches:
      - main
    paths:
      - RHMeLanding/**
  pull_request:
    branches:
      - main
    paths:
      - RHMeLanding/**
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v3
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_1528a30b5d32401385acfd5102e35647 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b53f4a22f35e4ddaaf588eb161658f13 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        context: ./RHMeLanding/
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8af1cbdaf22d4909b9e5a33c75d94a8f }}/hawkinsr/rhmelanding:${{ github.sha }}, index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8af1cbdaf22d4909b9e5a33c75d94a8f }}/hawkinsr/rhmelanding:latest
        file: ./RHMeLanding/Dockerfile

  deploy:
    runs-on: 'ubuntu-latest'
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'richardhawkinslanding'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6bb8e900796246f6aff3f4dc932f255d }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8af1cbdaf22d4909b9e5a33c75d94a8f }}/hawkinsr/rhmelanding:${{ github.sha }}'
